### PR TITLE
Static screens

### PR DESCRIPTION
**Pull request by Jia-A**
Screenshot (481)
Screenshot (482)

This PR contains 
 - Landing Page for Shoonya
 - Home Page for Shoonya
 - Sidebar
 - Navbar

### CODE REVIEW

**Review by Tanay-J — APPROVED** [review]
Good work! There are multiple comments in stylesheets, you may remove them before merging.

**Review by omjadhav85 — APPROVED** [review]
Looks good! You can abstract out the video card part to a different component later. For now, good to merge!

**Comment by Jia-A** [comment]
> Good work! There are multiple comments in stylesheets, you may remove them before merging.

oh yeah, forgot to do that.

**Comment by Jia-A** [comment]
> Looks good! You can abstract out the video card part to a different component later. For now, good to merge!

Okay, will do that.

**Pull request merged**
